name: Integration Tests
on:
  workflow_dispatch:
  #     inputs:
  #     platform:
  #       description: 'Log level'
  #       required: true
  #       default: 'warning'
  #       type: choice
  #       options:
  #       - info
  #       - warning
  #       - debug
      success:
        description: 'Did the tests pass?'
        required: true
        type: boolean
  #     environment:
  #       description: 'Environment to run tests against'
  #       type: environment
  #       required: true
jobs:
  mac:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ${{ inputs.success }}
